name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: dotnet build
      run: dotnet build Andromeda.Network.sln -c Release
      
    - name: dotnet test
      run: dotnet test Andromeda.Network.sln -c Release --no-build

    - name: dotnet pack
      run: dotnet pack Andromeda.Network.sln -c Release --no-build --output .

    - name: push packages
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
