name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build, pack & publish
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: dotnet build
      run: dotnet build Andromeda.Network.sln -c Release
      
    - name: dotnet test
      run: dotnet test Andromeda.Network.sln -c Release --no-build

    - name: dotnet pack
      run: dotnet pack Andromeda.Network.sln -c Release --no-build --include-symbols

    - name: setup nuget
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: NuGet/setup-nuget@v1.0.2
      with:
        nuget-version: latest

    - name: Set API key
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: nuget setapikey ${{ secrets.NUGET_API_KEY }}

    - name: push packages
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: dotnet nuget push **/*.nupkg --skip-duplicate
